name: Security Scan

on:
    schedule:
        # Run daily at 2 AM UTC
        - cron: "0 2 * * *"
    workflow_dispatch:

env:
    PNPM_VERSION: 8.15.0

jobs:
    dependency-audit:
        name: Dependency Audit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: ${{ env.PNPM_VERSION }}

            - uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Run security audit
              run: |
                  pnpm audit --audit-level moderate || exit_code=$?
                  if [ $exit_code -ne 0 ]; then
                    echo "::warning::Security vulnerabilities found"
                  fi

            - name: Check outdated packages
              run: pnpm outdated || true

    codeql:
        name: CodeQL Analysis
        runs-on: ubuntu-latest
        permissions:
            security-events: write
        steps:
            - uses: actions/checkout@v4

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: javascript,typescript

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3
